owid_covid_data<-read.csv ("owid-covid-data.csv", header=TRUE) 
owid_covid_data[is.na(owid_covid_data)]<- 0

m<-function(x){
  n <- length(x)
  y <- rep(0,n)
  for (i in 1:n){
    if (i <= 6){
      y[i] = mean(x[1:i])
    }else{
      y[i] = mean(x[(i-6):i])
    }
  }
  y
}
brazil<-subset(owid_covid_data,location=="Brazil")
brazil$new_cases<-abs(brazil$new_cases)
brazil$new_deaths<-abs(brazil$new_deaths)
brazil$date<-format(as.Date(brazil$date, format = "%m/%d/%Y"), "%Y-%m-%d")
brazil$year <- strftime(brazil$date, "%Y")    
brazil$month <- strftime(brazil$date, "%m")
brazil$dates<- strftime(brazil$date, "%d")
brazil$new_cases_tb<-m(brazil$new_cases)
brazil$new_cases_tb<-ceiling(brazil$new_cases_tb)
brazil$new_deaths_tb<-m(brazil$new_deaths)
brazil$new_deaths_tb<-ceiling(brazil$new_deaths_tb)
brazil_2020<-subset(brazil,(year=="2020"))
brazil_2021<-subset(brazil,(year=="2021"))
brazil_2022<-subset(brazil,(year=="2022"))
brazil_2020_3<-subset(brazil_2020,(month=="03"))
brazil_2020_6<-subset(brazil_2020,(month=="06"))
brazil_2020_7<-subset(brazil_2020,(month=="07"))
brazil_2021_1<-subset(brazil_2021,(month=="01"))
brazil_2021_3<-subset(brazil_2021,(month=="03"))
brazil_2021_6<-subset(brazil_2021,(month=="06"))
brazil_2021_7<-subset(brazil_2021,(month=="07"))
brazil_2022_1<-subset(brazil_2021,(month=="01"))

require(tidyr)
brazil_2020_3$cases_tichluy<-cumsum(replace_na(brazil_2020_3$new_cases_tb, 0))
brazil_2020_3$death_tichluy<-cumsum(replace_na(brazil_2020_3$new_deaths_tb, 0))
brazil_2020_6$cases_tichluy<-cumsum(replace_na(brazil_2020_6$new_cases_tb, 0))
brazil_2020_6$death_tichluy<-cumsum(replace_na(brazil_2020_6$new_deaths_tb, 0))
brazil_2020_7$cases_tichluy<-cumsum(replace_na(brazil_2020_7$new_cases_tb, 0))
brazil_2020_7$death_tichluy<-cumsum(replace_na(brazil_2020_7$new_deaths_tb, 0))

brazil_2021_1$cases_tichluy<-cumsum(replace_na(brazil_2021_1$new_cases_tb, 0))
brazil_2021_1$death_tichluy<-cumsum(replace_na(brazil_2021_1$new_deaths_tb, 0))
brazil_2021_3$cases_tichluy<-cumsum(replace_na(brazil_2021_3$new_cases_tb, 0))
brazil_2021_3$death_tichluy<-cumsum(replace_na(brazil_2021_3$new_deaths_tb, 0))
brazil_2021_6$cases_tichluy<-cumsum(replace_na(brazil_2021_6$new_cases_tb, 0))
brazil_2021_6$death_tichluy<-cumsum(replace_na(brazil_2021_6$new_deaths_tb, 0))
brazil_2021_7$cases_tichluy<-cumsum(replace_na(brazil_2021_7$new_cases_tb, 0))
brazil_2021_7$death_tichluy<-cumsum(replace_na(brazil_2021_7$new_deaths_tb, 0))

brazil_2022_1$cases_tichluy<-cumsum(replace_na(brazil_2021_1$new_cases_tb, 0))
brazil_2022_1$death_tichluy<-cumsum(replace_na(brazil_2021_1$new_deaths_tb, 0))

library(ggplot2)
ggplot()+geom_line(data=brazil_2020_3,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+geom_line(data=brazil_2020_6,(aes(x = dates, y = death_tichluy,group=1,col="red"))) +geom_line(data=brazil_2020_7,(aes(x = dates, y = death_tichluy,group=1,col="green")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 03,06,07-2020 cua Brazil",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 3", "thang 7","thang 6"), values= c( "blue","red", "green")) 
ggplot()+geom_line(data=brazil_2021_1,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+geom_line(data=brazil_2021_3,(aes(x = dates, y = death_tichluy,group=1,col="red"))) +geom_line(data=brazil_2021_6,(aes(x = dates, y = death_tichluy,group=1,col="green")))+geom_line(data=brazil_2021_7,(aes(x = dates, y = death_tichluy,group=1,col="orange")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 01,03,06,07-2021 cua Brazil",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 1", "thang 6","thang 7","thang 3"), values= c( "blue","red", "green","orange")) 
ggplot()+geom_line(data=brazil_2022_1,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 01-2022 cua Brazil",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 1"), values= c( "blue")) 



chile<-subset(owid_covid_data,location=="Chile")
chile$new_cases<-abs(chile$new_cases)
chile$new_deaths<-abs(chile$new_deaths)
chile$date<-format(as.Date(chile$date, format = "%m/%d/%Y"), "%Y-%m-%d")
chile$year <- strftime(chile$date, "%Y")    
chile$month <- strftime(chile$date, "%m")
chile$dates<- strftime(chile$date, "%d")
chile$new_cases_tb<-m(chile$new_cases)
chile$new_cases_tb<-ceiling(chile$new_cases_tb)
chile$new_deaths_tb<-m(chile$new_deaths)
chile$new_deaths_tb<-ceiling(chile$new_deaths_tb)
chile_2020<-subset(chile,(year=="2020"))
chile_2021<-subset(chile,(year=="2021"))
chile_2022<-subset(chile,(year=="2022"))
chile_2020_3<-subset(chile_2020,(month=="03"))
chile_2020_6<-subset(chile_2020,(month=="06"))
chile_2020_7<-subset(chile_2020,(month=="07"))
chile_2021_1<-subset(chile_2021,(month=="01"))
chile_2021_3<-subset(chile_2021,(month=="03"))
chile_2021_6<-subset(chile_2021,(month=="06"))
chile_2021_7<-subset(chile_2021,(month=="07"))
chile_2022_1<-subset(chile_2021,(month=="01"))

require(tidyr)
chile_2020_3$cases_tichluy<-cumsum(replace_na(chile_2020_3$new_cases_tb, 0))
chile_2020_3$death_tichluy<-cumsum(replace_na(chile_2020_3$new_deaths_tb, 0))
chile_2020_6$cases_tichluy<-cumsum(replace_na(chile_2020_6$new_cases_tb, 0))
chile_2020_6$death_tichluy<-cumsum(replace_na(chile_2020_6$new_deaths_tb, 0))
chile_2020_7$cases_tichluy<-cumsum(replace_na(chile_2020_7$new_cases_tb, 0))
chile_2020_7$death_tichluy<-cumsum(replace_na(chile_2020_7$new_deaths_tb, 0))

chile_2021_1$cases_tichluy<-cumsum(replace_na(chile_2021_1$new_cases_tb, 0))
chile_2021_1$death_tichluy<-cumsum(replace_na(chile_2021_1$new_deaths_tb, 0))
chile_2021_3$cases_tichluy<-cumsum(replace_na(chile_2021_3$new_cases_tb, 0))
chile_2021_3$death_tichluy<-cumsum(replace_na(chile_2021_3$new_deaths_tb, 0))
chile_2021_6$cases_tichluy<-cumsum(replace_na(chile_2021_6$new_cases_tb, 0))
chile_2021_6$death_tichluy<-cumsum(replace_na(chile_2021_6$new_deaths_tb, 0))
chile_2021_7$cases_tichluy<-cumsum(replace_na(chile_2021_7$new_cases_tb, 0))
chile_2021_7$death_tichluy<-cumsum(replace_na(chile_2021_7$new_deaths_tb, 0))

chile_2022_1$cases_tichluy<-cumsum(replace_na(chile_2021_1$new_cases_tb, 0))
chile_2022_1$death_tichluy<-cumsum(replace_na(chile_2021_1$new_deaths_tb, 0))


library(ggplot2)
ggplot()+geom_line(data=chile_2020_3,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+geom_line(data=chile_2020_6,(aes(x = dates, y = death_tichluy,group=1,col="red"))) +geom_line(data=chile_2020_7,(aes(x = dates, y = death_tichluy,group=1,col="green")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 03,06,07-2020 cua Chile",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 3", "thang 7","thang 6"), values= c( "blue","red", "green")) 
ggplot()+geom_line(data=chile_2021_1,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+geom_line(data=chile_2021_3,(aes(x = dates, y = death_tichluy,group=1,col="red"))) +geom_line(data=chile_2021_6,(aes(x = dates, y = death_tichluy,group=1,col="green")))+geom_line(data=chile_2021_7,(aes(x = dates, y = death_tichluy,group=1,col="orange")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 01,03,06,07-2021 cua Chile",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 1", "thang 6","thang 7","thang 3"), values= c( "blue","red", "green","orange")) 
ggplot()+geom_line(data=chile_2022_1,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 01-2022 cua Chile",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 1"), values= c( "blue"))


venezuela<-subset(owid_covid_data,location=="Venezuela")
venezuela$new_cases<-abs(venezuela$new_cases)
venezuela$new_deaths<-abs(venezuela$new_deaths)
venezuela$date<-format(as.Date(venezuela$date, format = "%m/%d/%Y"), "%Y-%m-%d")
venezuela$year <- strftime(venezuela$date, "%Y")    
venezuela$month <- strftime(venezuela$date, "%m")
venezuela$dates<- strftime(venezuela$date, "%d")
venezuela$new_cases_tb<-m(venezuela$new_cases)
venezuela$new_cases_tb<-ceiling(venezuela$new_cases_tb)
venezuela$new_deaths_tb<-m(venezuela$new_deaths)
venezuela$new_deaths_tb<-ceiling(venezuela$new_deaths_tb)
venezuela_2020<-subset(venezuela,(year=="2020"))
venezuela_2021<-subset(venezuela,(year=="2021"))
venezuela_2022<-subset(venezuela,(year=="2022"))
venezuela_2020_3<-subset(venezuela_2020,(month=="03"))
venezuela_2020_6<-subset(venezuela_2020,(month=="06"))
venezuela_2020_7<-subset(venezuela_2020,(month=="07"))
venezuela_2021_1<-subset(venezuela_2021,(month=="01"))
venezuela_2021_3<-subset(venezuela_2021,(month=="03"))
venezuela_2021_6<-subset(venezuela_2021,(month=="06"))
venezuela_2021_7<-subset(venezuela_2021,(month=="07"))
venezuela_2022_1<-subset(venezuela_2021,(month=="01"))

require(tidyr)
venezuela_2020_3$cases_tichluy<-cumsum(replace_na(venezuela_2020_3$new_cases_tb, 0))
venezuela_2020_3$death_tichluy<-cumsum(replace_na(venezuela_2020_3$new_deaths_tb, 0))
venezuela_2020_6$cases_tichluy<-cumsum(replace_na(venezuela_2020_6$new_cases_tb, 0))
venezuela_2020_6$death_tichluy<-cumsum(replace_na(venezuela_2020_6$new_deaths_tb, 0))
venezuela_2020_7$cases_tichluy<-cumsum(replace_na(venezuela_2020_7$new_cases_tb, 0))
venezuela_2020_7$death_tichluy<-cumsum(replace_na(venezuela_2020_7$new_deaths_tb, 0))

venezuela_2021_1$cases_tichluy<-cumsum(replace_na(venezuela_2021_1$new_cases_tb, 0))
venezuela_2021_1$death_tichluy<-cumsum(replace_na(venezuela_2021_1$new_deaths_tb, 0))
venezuela_2021_3$cases_tichluy<-cumsum(replace_na(venezuela_2021_3$new_cases_tb, 0))
venezuela_2021_3$death_tichluy<-cumsum(replace_na(venezuela_2021_3$new_deaths_tb, 0))
venezuela_2021_6$cases_tichluy<-cumsum(replace_na(venezuela_2021_6$new_cases_tb, 0))
venezuela_2021_6$death_tichluy<-cumsum(replace_na(venezuela_2021_6$new_deaths_tb, 0))
venezuela_2021_7$cases_tichluy<-cumsum(replace_na(venezuela_2021_7$new_cases_tb, 0))
venezuela_2021_7$death_tichluy<-cumsum(replace_na(venezuela_2021_7$new_deaths_tb, 0))

venezuela_2022_1$cases_tichluy<-cumsum(replace_na(venezuela_2021_1$new_cases_tb, 0))
venezuela_2022_1$death_tichluy<-cumsum(replace_na(venezuela_2021_1$new_deaths_tb, 0))


library(ggplot2)
ggplot()+geom_line(data=venezuela_2020_3,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+geom_line(data=venezuela_2020_6,(aes(x = dates, y = death_tichluy,group=1,col="red"))) +geom_line(data=venezuela_2020_7,(aes(x = dates, y = death_tichluy,group=1,col="green")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 03,06,07-2020 cua Venezuela",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 3", "thang 7","thang 6"), values= c( "blue","red", "green")) 
ggplot()+geom_line(data=venezuela_2021_1,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+geom_line(data=venezuela_2021_3,(aes(x = dates, y = death_tichluy,group=1,col="red"))) +geom_line(data=venezuela_2021_6,(aes(x = dates, y = death_tichluy,group=1,col="green")))+geom_line(data=venezuela_2021_7,(aes(x = dates, y = death_tichluy,group=1,col="orange")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 01,03,06,07-2021 cua Venezuela",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 1", "thang 6","thang 7","thang 3"), values= c( "blue","red", "green","orange")) 
ggplot()+geom_line(data=venezuela_2022_1,(aes(x = dates, y = death_tichluy,group=1,col="blue")))+labs(title = "Bieu do the hien thu thap tu vong tich luy vao cac thang 01-2022 cua Venezuela",subtitle = "Theo trung binh 7 ngay gan nhat",y = "So ca",x = "Ngay",color = "Chu thich")+scale_x_discrete(breaks=c("10","20","31"))+scale_color_manual(labels = c("thang 1"), values= c( "blue"))
